services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    restart: unless-stopped
    depends_on:
      - backend-api
    networks:
      - waste-collection

  backend-api:
    build:
      context: ./backend
      dockerfile: Dockerfile.api
    ports:
      - "5000:5000"
    restart: unless-stopped
    depends_on:
      - redis
    environment:
      - RESOURCES_PATH=/app
    volumes:
      - ./backend/resources:/app/resources
    expose:
      - "5000"
    networks:
      - waste-collection

  backend-path-checker:
    build:
      context: ./backend
      dockerfile: Dockerfile.path_checker
    restart: unless-stopped
    depends_on:
      - redis
    environment:
      - RESOURCES_PATH=/app
    volumes:
      - ./backend/resources:/app/resources
    networks:
      - waste-collection

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - waste-collection
    restart: unless-stopped
    command: redis-server --appendonly yes

networks:
  waste-collection:
